spring.application.name=cache
server.port=8443

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb   # Use 'mem' for an in-memory database
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa             # Default username for H2
spring.datasource.password=               # Default password is blank

# Redis configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# Optional: Cache name settings
spring.cache.cache-names=employees



